---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We were tasked with analyzing experimental data for dissolving times of brand name versus store brand cold medicine at
different water temperatures and stirring factors. We will explore the results to determine if differences do exist
between brand name and store brand medicine; if so, are they the result of temperature differences, stirring factors,
or both? 

The data was collected by dropping the medicine tablets into 60 mL of water of varying temperature (6$^\circ$, 23$^\circ$, 40$^\circ$) from a fixed height and recording the time it took the tablet to completely dissolve from the time it was dropped. The stirring factor was used as a blocking method; Block I was stirred while Block II was not. Four different individuals performed the experiment and recorded their results; the average of these results were recorded
as the observations.  

A summary statistics table shows there is, indeed, a difference in mean dissolve time between name brand and store brand. A means table shows name brand has a mean of 73.443 with variance of 21.131, while store brand has a mean of 68.104 and variance of 67.032. Our findings also showed that stirring appears to increase variability in name brand while decreasing variability in store brand. Additionally, plots of the data show a meaningful interaction between brand and temperature, which becomes more prominent at higher temperatures.

8 models were fit in total: 3 for fixed effects, 3 for mixed effects, and 2 for adding the `order` variable as a covariate. Model 1, which we have referred to as "the full model", includes a three-way interaction between brand, temp, and stirred and produced the lowest Root Mean Square Error (RMSE) of 1.075. Model 8, which used the full model but added `order` as covariate measure, produced a RMSE of 1.083 (the 2nd lowest RMSE). We chose the best model by using the common fit criteria RMSE, Adjusted R^2^, AIC, and BIC. For RMSE, AIC, and BIC, lower values are better, while a higher value of Adjusted R^2^ is preferred as it explains the percentage of variation explained by the model. Model 1 produced the best results across all four model selection criteria with RMSE of 1.075, Adjusted R^2^ of 0.977, AIC of 155.337, and BIC of 179.663. Model 1's assumptions of normality and constant variance are generally met, despite having slightly heavy tails and mild heteroscedasticity. The Cook's Distance plot shows observations 2, 3, and 8 potentially being problematic outliers, but because the values were all under 0.5, we chose to leave them in the analysis to avoid creating imbalances.

An Analysis of Variance (ANOVA) was conducted for the full model to check differences and run several hypothesis tests. A significant result is declared when the F critical value (F-crit) is less than the calculated F-score. The results showed that there is at least one difference in means (F-crit = 2.06, F-score = 183.21) and there are significant interactions between brand and temperature (F-crit = 3.2594, F-score = 100.3688), brand and stirring (F-crit = 4.1132, F-score = 17.758), and brand, temperature, and stirring (F-crit = 3.2594, F-score = 3.919). The same analysis also showed that there is not sufficient evidence to claim meaningful interactions between temperature and stirring (F-crit = 3.2594, F-score = 0.0537).  

A number of contrast analyses were conducted to see how much the significant means differed from one another. Our findings showed that, on average, stirring medicine reduces dissolving time by 1.78 to 3.04 seconds, name brand medicine dissolves between 4.71 and 5.97 seconds slower than store brand, and stirring reduces name brand dissolving time by 2.83 to 4.61 seconds compared to 0.22 to 2 seconds for store brand. Pairwise analyses were conducted for the three levels of temperature using Bonferroni correction which showed significant differences for each of the pairs. The 95% confidence limits were (6.25, 8.38), (13.32, 15.44), and (6.00, 8.13) for the pair wise comparisons of $6^\circ C~vs~23^\circ C$, $6^\circ C~vs~40^\circ C$, and $23^\circ C~vs~40^\circ C$, respectively. When comparing each temperature to the remainder of the group, $23^\circ C$ was not significantly different.  

To recap, we have determined that, on average, name brand dissolving times are between 4.71 and 5.97 seconds slower than store brands, water temperature has an inverse relationship with dissolving times, there is a highly significant interaction between brand and temperature, and stirring reduces dissolving time by 1.78 and 3.04 seconds. Stirring was found to have a highly significant interaction with brand (p=0.0002) and a significant interaction with both brand and temperature (p=0.029); because these interactions are so significant, we suggest using stirring as a main effect rather than a blocking variable.


